%YAML:1.0

enable_debug: false

# For CalibParamManager
# optimization
gyro_weight: 1.0
accel_weight: 1.0
imu_ba_weight: 1.
imu_bg_weight: 1.

imu_pos_weight: 1.
imu_vel_weight: 1.
imu_rot_weight: 1.
imu_pos_weight_li: 5.
imu_vel_weight_li: 5.
imu_rot_weight_li: 5.
imu_pos_weight_vi: 30.
imu_vel_weight_vi: 30.
imu_rot_weight_vi: 30.

cam_uv_weight: 5.  
cam_rot_weight: 50.
cam_pos_weight: 20.

lidar_weight: 30.

lidar_rot_weight: 50.0
lidar_pos_weight: 30.0

window_length: 1.0
imu_excite_threshold: 0.5
gravity: [0., 0., -9.7803]
gravity_norm: -9.7803
g_norm_for_debug: -9.7803
vio_time_window: 0.5

knot_space: 0.1

enable_imu_orientation: false
enable_imu_interpolated_pose: false
enable_imu_predicted_pose: false

enable_depth_assiciation: false

num_anchor: 30
sample_num: 5
num_bins: 360
max_cnt: 150

# feature tracking
window_size: 10
n_grid_rows: 8
n_grid_cols: 8

visual_depth_lower_bound: 0.5
visual_depth_upper_bound: 100.

# if the reprojection error of this observation is larger than this threshold, it would be regarded as an outlier which to be removed or reweighted.
reproject_outlier_threshold: 0.05
remove_outlier: false
reweight_outlier: true
# the new weight of this observation would be cam_uv_weight * reweight_outlier_scale
reweight_outlier_scale: 0.

gyro_bias_uppper_bound: 0.3
acce_bias_uppper_bound: 0.5

accel_excite_threshold: 0.25
gyro_excite_threshold: 0.25

# set zero to disable random dropping scans
random_drop_num: 0
visual_terms_number: 500
ndt_resolution: 1.0

# max time of ceres solver for LVI optimization
max_time_cost: 0.05

### VIRAL ###
time_offset_lidar: 0.
# time_offset_camera: -0.0199575325817
time_offset_camera: 0.

extrinsic_LtoI:
 Trans: [-0.05, 0., 0.055]
 Rot: [1, 0, 0, 0, 1, 0, 0, 0, 1]

extrinsic_CtoI:
 Trans: [0.00552943, -0.12431302, 0.01614686]
 Rot: [0.02183084, -0.01312053,  0.99967558, 
       0.99975965,  0.00230088, -0.02180248, 
       -0.00201407,  0.99991127,  0.01316761]

mask: ""
image_sampling_ratio: 0.5
model_type:   PINHOLE
camera_name:  left-camera
image_width:  752
image_height: 480
distortion_model: radial-tangential
distortion_parameters:
   k1: -0.288105327549552
   k2:  0.074578284234601
   p1:  7.784489598138802e-04
   p2: -2.277853975035461e-04
projection_parameters:
   fx: 4.250258563372763e+02
   fy: 4.267976260903337e+02
   cx: 3.860151866550880e+02
   cy: 2.419130336743440e+02

seg_threshold: 0.1
seg_inlier_ratio: 0.9

VINS:
  focal_length: 460.
  init_depth: 5.
  
  #feature traker paprameters
  max_cnt: 150            # max feature number in feature tracking
  min_dist: 20            # min distance between two features 

  #optimization parameters
  solver_time: 0.04  # max solver itration time (ms), to guarantee real time
  num_iterations: 8   # max solver itrations, to guarantee real time
  min_parallax: 10.0 # keyframe selection threshold (pixel)

  #imu parameters       The more accurate parameters you provide, the better performance
  acc_n: 0.02          # accelerometer measurement noise standard deviation. #0.2   0.04
  gyr_n: 0.01        # gyroscope measurement noise standard deviation.     #0.05  0.004
  acc_w: 0.002         # accelerometer bias random work noise standard deviation.  #0.02
  gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
  g_norm: 9.805     # gravity magnitude
  
  bias_acc_threshold: 0.2
  bias_gyr_threshold: 0.2

  #unsynchronization parameters
  estimate_td: 0                      # online estimate time offset between camera and imu
  td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

  #rolling shutter parameters
  rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
  tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 
  enable_state_factor: false
  fix_depth_associated: false
  weight_pos: 30
  weight_rot: 30
  weight_vel: 10
  weight_ba: 5
  weight_bg: 5